### ISSUE TITLE
New prop initialStepIndex

### ISSUE THREAD

**Issue by kaYcee** [Jibbedi/react-wizard-primitive#26]
First of all, great lib, very useful! Would it possible to include an `initialStepIndex` property where the wizard initially starts? In our use case we store the current step locally. In case the user refreshes the page, the wizard starts from its last index. Currently, we use `goToStep` to achieve this once the wizard is loaded, but it results in a noticeable glitch on slow devices.

I should mention that routing is not an option for us since we don't want the user to mess around with the wizards state.

**Comment by Jibbedi** [comment]
Hey! Thanks for the feedback - I really appreciate it! :-)

And yep we can definitely do that. Sounds like a great addition. 
I'll give it a shot at the weekend and it should be released by monday.

**Comment by kaYcee** [comment]
thx @Jibbedi for the quick implementation! works like a charm.

**Comment by Jibbedi** [comment]
You're welcome @kaYcee. I've also added you as a [contributor](https://github.com/Jibbedi/react-wizard-primitive/#contributors) for your idea :-)
