### ISSUE TITLE
Add option to skip onChange handler when calling goToStep

### ISSUE THREAD

**Issue by kaldebert** [Jibbedi/react-wizard-primitive#34]
Thank you for this library!
Would it possible to add an option to skip `onChange` handler when calling `goToStep`?
In my case, I push a new state to the browser's session history stack (see [history](https://github.com/ReactTraining/history)) thank to the `onChange` handler. I don't use hash routing so I can't use the built-in routing.
I have also a listener to `popstate` event that updates current step (by calling `goToStep`) when the user clicks on back button for example. In this case, I would like to skip the `onChange` handler. Otherwise it pushes a new state and breaks the navigation.

Example:
```
  const { activeStepIndex, getStep, goToStep, nextStep, previousStep } = useWizard({
      onChange: ({ newStepIndex }) => {
        history.push("/step" + newStepIndex);
      }
  });

  useEffect(() => {
    const handlePopState = event => {
      // retrieve step index from path
      const newStepIndex = ...;
      if (newStepIndex !== -1) {
        // actually
        goToStep(newStepIndex);
        // expected
        goToStep(newStepIndex, { skipOnChange: true });
      }
    };

    window.addEventListener("popstate", handlePopState);

    return () => {
      window.removeEventListener("popstate", handlePopState);
    };
  });
```

**Comment by Jibbedi** [comment]
Hey!

Thanks for reaching out =)

We can definitely figure something out there. Give me a few days (I hope I can get to this before the weekend) to think about this =)
