### ISSUE TITLE
Disabled routing

### ISSUE THREAD

**Issue by carscx** [Jibbedi/react-wizard-primitive#39]
Is there any possibility to disable the router? thanks

**Comment by Jibbedi** [comment]
Hey Carlos,

thanks for reaching out. :-)
Actually routing should be disabled by default unless you specify a `routeTitle` for every step. 

Have you tried removing those?

**Comment by carscx** [comment]
I am not using the WizardStep component, just the hook. And in the url of my site # / undefined appears


`  const { nextStep, previousStep, activeStepIndex, getStep } = useWizard()

...

{examQuestions.map(
                      (q, i) =>
                        getStep().isActive && (
                          <BoxQuestion key={i}>
                            {q.question_choice ? (
                              <QuestionChoice
                                idQuestion={q.id}
                                handleChoice={handleChoice}
                                questionChoice={q.question_choice}
                              />
                            ) : q.question_write ? (
                              <div>
                                <QuestionWrite
                                  questionWrite={q.question_write}
                                />
                              </div>
                            ) : q.question_file ? (
                              <div>
                                <QuestionFile questionFile={q.question_file} />
                              </div>
                            ) : (
                              ''
                            )}
                          </BoxQuestion>
                        )
                    )}


`

**Comment by Jibbedi** [comment]
Okay that's interesting. 
Just tried to recreate that issue and couldn't. 

https://codesandbox.io/s/gifted-archimedes-cner0?file=/src/App.js

Could you provide me with a minimal example code that is not working?

Are you on the latest version which is `2.3.0`?
Otherwise could you try `getStep({routeTitle: null})` to see if this helps?

**Comment by andreibeneatol** [comment]
Hello, I think this is a real issue. I am encountering the same thing. It seems to be happening when hooks get initialised.

`  
const { nextStep, previousStep, activeStepIndex, getStep, moveToStep } = useWizard()
`

**Comment by Jibbedi** [comment]
Oh interesting. I'll try to reproduce it with React router. Thanks for your input :)

Would you mind sharing your code that causes the issue?

**Comment by andreibeneatol** [comment]
I have a component rendered with react router and within that component I started building the custom wizard. It seems to be enough to call `useWizard()` and #undefined is added at the end of the route.

**Comment by andreibeneatol** [comment]
Most likely it is caused by this line from getRoutingHash.
`getWindow() ? getWindow().location.hash.replace("#", "") : undefined;`

An easy fix might be what @carscx proposed, add the possibility to disable the routing and everything should be fine

**Comment by carscx** [comment]
Sorry for not answering in so long. As an alternative, I have done the following, at least until there is a chance to disable the route.

`history.replaceState({}, document.title, window.location.href.split('#')[0])`

**Comment by Jibbedi** [comment]
Alright I figured it out :-)

As i mentioned routing is disabled unless you specify routeTitles.

However, the implementation has a bug when the getStep is not called on the initial render. For example, when they're rendered conditionally or after an API call has been issued.

Is that the case for both for you? I was able to reproduce that and you can expect a fix soon :-)

**Comment by Jibbedi** [comment]
@carscx  @andreibeneatol 
I've added you as contributors for finding this bug :-)
If you feel uncomfortable with it, just let me know and I'll remove you.

Thanks.

**Comment by carscx** [comment]
Is Ok, No problem, thank's to you for your rapid resolution.
