### ISSUE TITLE
README.md small improvements

### ISSUE THREAD

**Issue by Uzwername** [Jibbedi/react-wizard-primitive#53]
Hey,

This is a question about a possible first-time contribution.

I found several small improvements that could be applied to `README.md` file (typos, duplicated lines).

Can I go ahead & submit a pull request? Is there anything I should do before?

**Comment by Jibbedi** [comment]
Hey,

that would be great and much appreciated!

Sure feel free to go ahead. 
Thanks! :-)

**Comment by Uzwername** [comment]
@Jibbedi Ok, thanks! Here is my pull request #54
